services:


  reverse-proxy:
    image: nginx:1.27.0-perl
    container_name: reverse_proxy
    ports:
      - 8888:80
    volumes:
      - ./setup/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
    networks:
      - app-network


  keycloak:
      image: keycloak/keycloak:25.0
      container_name: keycloak
      environment:
        - KC_PROXY_HEADERS=xforwarded
        - KC_HTTP_ENABLED=true
        - KC_PROXY=edge
        - KC_HOSTNAME_STRICT=false
        - DB_VENDOR=postgres
        - DB_ADDR=postgres
        - DB_DATABASE=keycloakdb
        - DB_USER=keycloak
        - DB_PASSWORD=keycloakdbpass
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://postgres/keycloakdb
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=keycloakdbpass
        - KEYCLOAK_IMPORT=/tmp/realm-test.json
        - PROXY_ADDRESS_FORWARDING=true
      expose:
        - "8080"
      volumes:
      - ./setup/:/opt/keycloak/data/import
      depends_on:
        - postgres
      networks:
      - app-network
      command: 
        - start-dev
        - --import-realm


  postgres:
      image: postgres:16.3-alpine3.20
      container_name: postgres
      environment:
        - POSTGRES_DB=keycloakdb
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloakdbpass
      expose:
        - "5432"
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
      - app-network


  streamlit_app:
    build: ./streamlit_app/
    container_name: streamlit_app
    environment:
      - AUTHORIZE_URL=http://localhost:8888/realms/test/protocol/openid-connect/auth
      - TOKEN_URL=http://keycloak:8080/realms/test/protocol/openid-connect/token
      - REFRESH_TOKEN_URL=http://keycloak:8080/realms/test/protocol/openid-connect/token
      - REVOKE_TOKEN_URL=http://keycloak:8080/realms/test/protocol/openid-connect/revoke
      - CLIENT_ID=test_client
      #This is a dummy secret just for test purposes, never put client secret here, use .env instead !
      - CLIENT_SECRET=6fLF6yvAUm9bzrxiDgMfIC4VOIfT9gep
      - REDIRECT_URI=http://localhost:8501
      - SCOPE=openid email profile
    ports:
      - 8501:8501
    expose:
      - "8501"
    depends_on:
      - keycloak
      - postgres
    networks:
      - app-network


volumes:
  postgres:

networks:
  app-network:
    driver: bridge