services:

  keycloak:
      image: keycloak/keycloak:25.0
      container_name: keycloak
      ports:
        - 3000:8080
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - DB_VENDOR=postgres
        - DB_ADDR=postgres
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=keycloak
      depends_on:
        - postgres
      command: ["start-dev"]

  postgres:
      image: postgres:16.3-alpine3.20
      container_name: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - postgres:/var/lib/postgresql/data
        - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql.sql

volumes:
  postgres: