services:

  keycloak:
      image: keycloak/keycloak:25.0
      container_name: keycloak
      ports:
        - 3000:8080
      environment:
        - DB_VENDOR=postgres
        - DB_ADDR=postgres
        - DB_DATABASE=keycloakdb
        - DB_USER=keycloak
        - DB_PASSWORD=keycloakdbpass
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://postgres/keycloakdb
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=keycloakdbpass
        - KEYCLOAK_IMPORT=/tmp/realm-test.json
      volumes:
      - ./setup/:/opt/keycloak/data/import
      depends_on:
        - postgres
      command: 
        - start-dev
        - --import-realm

  postgres:
      image: postgres:16.3-alpine3.20
      container_name: postgres
      expose:
        - "5432"
      environment:
        - POSTGRES_DB=keycloakdb
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloakdbpass
      volumes:
        - postgres:/var/lib/postgresql/data

  streamlit_app:
    build: ./streamlit_app/
    depends_on:
      - keycloak
      - postgres
    env_file:
      - .env
    ports:
      - 8501:8501
    expose:
      - "8501"

volumes:
  postgres: